FROM python:3.11-alpine

WORKDIR /app

COPY . /app

RUN apk add --no-cache git && \
    git clone https://github.com/minhee231/JihwanTalmo.git && \
    cp JihwanTalmo/backend/module/CtrlJson.py /app/CtrlJson.py && \
    cp JihwanTalmo/backend/module/Encryption.py /app/Encryption.py

RUN pip3 install --no-cache-dir -r requirements.txt

ENV FLASK_RUN_PORT=429

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]