FROM python:3.8-alpine

WORKDIR /app

COPY . /app

RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev

RUN pip3 install --no-cache-dir -r requirements.txt

ENV FLASK_RUN_PORT=5000

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
