FROM python:3.11-alpine

WORKDIR /app

COPY . /app

#모듈 불러오기
RUN apk add --no-cache git && \
    git clone https://github.com/minhee231/JihwanTalmo.git && \
    cp JihwanTalmo/backend/module/CtrlJson.py /app/CtrlJson.py

RUN pip3 install --no-cache-dir -r requirements.txt

#포트 지정임
ENV FLASK_RUN_PORT=687

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]