FROM python:3.11-alpine

# 필요한 패키지 설치
RUN apk add --no-cache git

WORKDIR /app

# Git 저장소 설정
RUN git init \
    && git remote add origin https://github.com/minhee231/JihwanTalmo.git \
    && git config core.sparseCheckout true \
    && echo "backend/module/*" >> .git/info/sparse-checkout \
    && git pull origin main \
    && mv backend/module/* . \
    && rm -rf backend .git

# 필요한 Python 패키지 설치
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# 환경 변수 설정
ENV FLASK_RUN_PORT=5000

# 컨테이너 실행 시 Flask 애플리케이션 실행
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
